"""initial migration

Revision ID: 056bb2467afb
Revises: 7126d9e92ad5
Create Date: 2018-05-30 12:02:54.016131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '056bb2467afb'
down_revision = '7126d9e92ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_ibfk_3', 'posts', type_='foreignkey')
    op.drop_column('posts', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_ibfk_3', 'posts', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
