"""initial migration

Revision ID: 08dcba24b0e9
Revises: 6b7506806695
Create Date: 2018-05-12 15:21:58.913888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08dcba24b0e9'
down_revision = '6b7506806695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idle_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('descriptions', sa.Text(), nullable=True),
    sa.Column('images', sa.String(length=128), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('view_times', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idle_items_title'), 'idle_items', ['title'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('idle_items_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idle_items_id'], ['idle_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_idle_itmes_title', table_name='idle_itmes')
    op.drop_table('idle_itmes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idle_itmes',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('descriptions', mysql.TEXT(), nullable=True),
    sa.Column('images', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('add_time', mysql.DATETIME(), nullable=True),
    sa.Column('view_times', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='idle_itmes_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_idle_itmes_title', 'idle_itmes', ['title'], unique=False)
    op.drop_table('comments')
    op.drop_index(op.f('ix_idle_items_title'), table_name='idle_items')
    op.drop_table('idle_items')
    # ### end Alembic commands ###
