"""initial migration

Revision ID: 4d426c9d31f1
Revises: b16cd28f8eee
Create Date: 2018-05-27 22:55:09.760297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d426c9d31f1'
down_revision = 'b16cd28f8eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_messages')
    # ### end Alembic commands ###
