"""initial migration

Revision ID: 53bf00df7267
Revises: 874088c37206
Create Date: 2018-05-20 13:39:22.039758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53bf00df7267'
down_revision = '874088c37206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messageboard', sa.Column('add_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messageboard', 'add_time')
    # ### end Alembic commands ###
