"""initial migration

Revision ID: 561b97e39e5e
Revises: 1f5406aca136
Create Date: 2018-05-11 13:16:52.492375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561b97e39e5e'
down_revision = '1f5406aca136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idle_itmes', sa.Column('add_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idle_itmes', 'add_time')
    # ### end Alembic commands ###
