"""initial migration

Revision ID: 6b7506806695
Revises: 561b97e39e5e
Create Date: 2018-05-11 23:33:40.112127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7506806695'
down_revision = '561b97e39e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idle_itmes', sa.Column('view_times', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idle_itmes', 'view_times')
    # ### end Alembic commands ###
