"""initial migration

Revision ID: b93258746a1f
Revises: 4d426c9d31f1
Create Date: 2018-05-30 11:59:25.818365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b93258746a1f'
down_revision = '4d426c9d31f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_ibfk_1', 'posts', type_='foreignkey')
    op.drop_column('posts', 'category_id')
    op.drop_column('posts', 'images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('images', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('posts', sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_ibfk_1', 'posts', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
