"""initial migration

Revision ID: e47234679eb7
Revises: 990f17a027ab
Create Date: 2018-05-15 16:58:20.451287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47234679eb7'
down_revision = '990f17a027ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replys_to_comment', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'replys_to_comment', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'replys_to_comment', type_='foreignkey')
    op.drop_column('replys_to_comment', 'user_id')
    # ### end Alembic commands ###
