"""initial migration

Revision ID: ed6351ac8239
Revises: 08dcba24b0e9
Create Date: 2018-05-12 17:04:35.951782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed6351ac8239'
down_revision = '08dcba24b0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('idle_item_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_ibfk_1', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'idle_items', ['idle_item_id'], ['id'])
    op.drop_column('comments', 'idle_items_id')
    op.add_column('idle_items', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'idle_items', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'idle_items', type_='foreignkey')
    op.drop_column('idle_items', 'user_id')
    op.add_column('comments', sa.Column('idle_items_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_ibfk_1', 'comments', 'idle_items', ['idle_items_id'], ['id'])
    op.drop_column('comments', 'idle_item_id')
    # ### end Alembic commands ###
