"""initial migration

Revision ID: f6fe527e5f45
Revises: 42533cd7f510
Create Date: 2018-06-10 15:51:48.403775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6fe527e5f45'
down_revision = '42533cd7f510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('check', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'check')
    # ### end Alembic commands ###
